import { MemberCardProps } from "../src/MemberCard";

export const membros: MemberCardProps[] = [
  {
    name: "Ralph dos Santos Silva",
    role: "docente",
    image: "https://avatars.githubusercontent.com/u/138714255?v=4",
    description: [
      "Professor Associado",
      "Departamento de Métodos Estatísticos",
      "Instituto de Matemática",
    ],
    page: "https://www.im.ufrj.br/ralph",
    institution: "Universidade Federal do Rio de Janeiro",
    lattes: "http://lattes.cnpq.br/1513109865941797",
    ORCID: "https://orcid.org/0000-0002-4311-6762",
    linkedin: "https://www.linkedin.com/in/ralph-silva-a82929297/",
    github: "https://github.com/ralphssilva",
  },
  {
    name: "Marcus L. Nascimento",
    role: "discente",
    image: "https://avatars.githubusercontent.com/u/77112876?v=4",
    description: ["Pesquisador", "Departamento de Pesquisa"],
    institution: "Fundação José Luiz Egydio Setúbal",
    lattes: "https://lattes.cnpq.br/5803567335277582",
    ORCID: "https://orcid.org/0000-0002-9742-5683",
    github: "https://github.com/marcuslavagnole",
  },
  {
    name: "Paulo Silva Filho",
    role: "discente",
    image:
      "http://servicosweb.cnpq.br/wspessoa/servletrecuperafoto?tipo=1&id=K4766525H3",
    description: ["Graduando em Matematica Aplicada"],
    institution: "Universidade Federal do Rio de Janeiro",
    lattes: "http://lattes.cnpq.br/1370344932631721",
    linkedin: "https://www.linkedin.com/in/paulo-silva-filho-9584852a",
    github: "https://github.com/ultraschemer",
  },
  {
    name: "Heudson Tosta Mirandola",
    role: "docente",
    image: "https://avatars.githubusercontent.com/u/20370158?v=4",
    description: ["Professor Associado", "Departamento de Matemática"],
    institution: "Universidade Federal do Rio de Janeiro",
    lattes: "http://lattes.cnpq.br/3030808069800164",
    github: "https://github.com/mirandola",
  },
  {
    name: "Matheus Vargas",
    role: "discente",
    image:
      "http://servicosweb.cnpq.br/wspessoa/servletrecuperafoto?tipo=1&id=K1190780Y5",
    description: ["Graduando em Ciência da Computação"],
    institution: "Universidade Federal do Rio de Janeiro",
    lattes: "https://lattes.cnpq.br/4974056898006345",
    github: "https://github.com/theuvargas",
    linkedin: "https://www.linkedin.com/in/theu-vargas/",
  },
  {
    name: "Rafael Schmidt",
    role: "discente",
    image: "https://avatars.githubusercontent.com/u/42819312?v=4",
    description: ["Graduando em Ciência da Computação"],
    institution: "Universidade Federal do Rio de Janeiro",
    page: "https://www.rafaelschmidt.tech/",
    lattes: "http://lattes.cnpq.br/7268820680153831",
    github: "https://github.com/Ralfe15",
    linkedin: "https://www.linkedin.com/in/rafael-schmidt-838075194/",
  },
  {
    name: "Wladimir Augusto das Neves",
    role: "docente",
    image:
      "http://servicosweb.cnpq.br/wspessoa/servletrecuperafoto?tipo=1&id=K4784134T8",
    lattes: "http://lattes.cnpq.br/2097908108919241",
    description: [
      "Professor Associado",
      "Departamento de Matemática",
      "Instituto de Matemática",
    ],
    institution: "Universidade Federal do Rio de Janeiro",
  },
  {
    name: "Pedro Saito",
    role: "discente",
    image: "http://servicosweb.cnpq.br/wspessoa/servletrecuperafoto?tipo=1&id=K1133521Z9",
    description: ["Graduando em Ciência da Computação"],
    institution: "Universidade Federal do Rio de Janeiro",
    lattes: "http://lattes.cnpq.br/1584609256466864",
    github: "https://github.com/saitoi",
    linkedin: "https://www.linkedin.com/in/pedro-saito-419a08247/"
  },
];
